# Generated by Django 3.2.19 on 2023-05-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonorDetailsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('Home_address', models.CharField(max_length=250)),
                ('office_address', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=50)),
                ('last_time_blood_donated', models.CharField(max_length=100)),
                ('did_you_ever_donate_blood_before', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20)),
                ('Are_you_currently_taking_any_medications', models.TextField()),
                ('Do_you_have_any_disease', models.TextField()),
            ],
        ),
    ]
